"""Read-only provider evidence admission. No provider calls or vault writes.

Adapters implement the published producer manifest contracts, with checked-in
fixtures generated by the actual producers. Hashes prove integrity, not truth.
"""
from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any

from .ledgers import strict_json_loads
from .paths import assert_unaliased_directory, is_name_surrogate
from .transaction import read_vault_regular

SCHEMAS = {"legends-research-evidence/v1": "dataforseo",
           "legends-firecrawl-evidence/v1": "firecrawl"}
MAX_RESPONSE_BYTES = 64 * 1024 * 1024
_HEX = re.compile(r"^[0-9a-f]{64}$")


class EvidenceError(ValueError):
    """Invalid or out-of-scope evidence; messages do not include source contents."""


def _hash(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _canonical(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, ensure_ascii=False, indent=2,
                      allow_nan=False).encode("utf-8")


def _directory(path: Path) -> Path:
    # Do not resolve away a linked ancestor before inspecting it. These checks
    # supplement the shared no-follow bounded reader; they are not a sandbox.
    path = Path(path).expanduser().absolute()
    for item in (path, *path.parents):
        assert_unaliased_directory(item)
    return path


def _firecrawl_state(data: dict, endpoint: str) -> str:
    status = data.get("status")
    if data.get("success") is False or status in ("error", "failed", "cancelled"):
        return "error"
    if status in ("scraping", "pending", "queued", "processing", "in_progress") or endpoint == "crawl":
        return "pending"
    if "status" in data and status not in ("empty", "completed", "ok"):
        return "unknown"
    if isinstance(data.get("response"), dict) and data["response"].get("success") is False:
        return "error"
    if status == "empty":
        return "empty"
    if data.get("next"):
        return "partial"
    if status in ("completed", "ok") or data.get("success") is True:
        return "empty" if data.get("data", data.get("links")) in (None, [], {}) else "completed"
    return "unknown"


def _dataforseo_state(data: dict) -> str:
    tasks = data.get("tasks")
    if not isinstance(tasks, list) or any(not isinstance(t, dict) for t in tasks):
        raise EvidenceError("invalid DataForSEO task envelope")
    codes = [data.get("status_code"), *[t.get("status_code") for t in tasks]]
    if any(c in (20100, 20101, 20102, 40601, 40602) for c in codes):
        return "pending"
    if any(c != 20000 for c in codes):
        return "error"
    if not tasks or any(not t.get("result") for t in tasks):
        return "empty"
    return "completed"


def verify_package(package: Path | str, *, workspace: str) -> dict[str, Any]:
    """Verify fixed package members and return metadata only, never raw contents."""
    if not isinstance(workspace, str) or not workspace.strip():
        raise EvidenceError("explicit client/workspace identity required")
    root = _directory(Path(package))
    blobs = {}
    for name, limit in (("manifest.json", 2_000_000), ("README.md", 2_000_000),
                        ("response.json", MAX_RESPONSE_BYTES)):
        if is_name_surrogate((root / name).lstat()):
            raise EvidenceError("linked evidence member refused")
        blobs[name] = read_vault_regular(root, name, limit=limit, missing_ok=False)
    try:
        manifest = strict_json_loads(blobs["manifest.json"].decode("utf-8"))
        raw = strict_json_loads(blobs["response.json"].decode("utf-8"))
        blobs["README.md"].decode("utf-8")
        if not isinstance(manifest, dict) or not isinstance(raw, dict):
            raise EvidenceError("manifest and response must be JSON objects")
        schema = manifest.get("schema")
        if schema not in SCHEMAS:
            raise EvidenceError("unsupported evidence schema")
        identity = manifest.get("evidence_id")
        if not isinstance(identity, str) or not _HEX.fullmatch(identity):
            raise EvidenceError("invalid evidence identity")
        unsigned = {k: v for k, v in manifest.items() if k != "evidence_id"}
        if _hash(_canonical(unsigned)) != identity:
            raise EvidenceError("manifest integrity mismatch")
        if manifest.get("workspace") != workspace:
            raise EvidenceError("workspace differs from explicitly selected client scope")
        endpoint = manifest.get("endpoint")
        if not isinstance(endpoint, str) or not endpoint.strip():
            raise EvidenceError("endpoint required")
        request = manifest.get("request")
        if not isinstance(request, (dict, list)) or not request:
            raise EvidenceError("complete request/settings required")
        if not isinstance(manifest.get("producer"), str) or not manifest["producer"].strip():
            raise EvidenceError("producer required")
        observed = manifest.get("observed_at")
        date = datetime.fromisoformat(observed.replace("Z", "+00:00"))
        if date.tzinfo is None:
            raise EvidenceError("observation time requires timezone")
        if _hash(blobs["response.json"]) != manifest.get("response_sha256"):
            raise EvidenceError("response integrity mismatch")
        note_hash = manifest.get("note_sha256")
        if "note_sha256" in manifest and _hash(blobs["README.md"]) != note_hash:
            raise EvidenceError("note integrity mismatch")
        if schema == "legends-research-evidence/v1":
            state = _dataforseo_state(raw)
            tasks = [{k: t.get(k) for k in ("id", "status_code", "cost")} for t in raw["tasks"]]
            if (manifest.get("tasks") != tasks or manifest.get("status_code") != raw.get("status_code")
                    or manifest.get("reported_response_cost") != raw.get("cost")):
                raise EvidenceError("manifest metadata differs from response")
        else:
            if manifest.get("provider") != "firecrawl" or not isinstance(request, dict):
                raise EvidenceError("invalid Firecrawl provider/request contract")
            if note_hash is None:
                raise EvidenceError("Firecrawl note hash required")
            if manifest.get("coverage") != {"scope": "single_response", "completeness": "not_asserted"}:
                raise EvidenceError("unsupported Firecrawl coverage contract")
            state = _firecrawl_state(raw, endpoint)
            if manifest.get("status") != state:
                raise EvidenceError("manifest state differs from response")
    except (KeyError, TypeError, AttributeError, UnicodeError, ValueError) as exc:
        if isinstance(exc, EvidenceError):
            raise
        raise EvidenceError("invalid evidence JSON or metadata") from exc
    return {"schema": "legends-empire.evidence-verification/v1", "verified": True,
            "package_schema": schema, "provider": SCHEMAS[schema],
            "workspace": workspace, "evidence_id": identity, "observed_at": observed,
            "response_state": state, "response_integrity": "verified",
            "note_integrity": "verified" if note_hash else "not_recorded",
            "files": [{"path": name, "sha256": _hash(content), "bytes": len(content)}
                      for name, content in blobs.items()],
            "provider_calls": 0, "writes": 0, "requires_semantic_review": True,
            "freshness_assessed": False, "canonical_promotion": False}


def plan_intake(package: Path | str, *, workspace: str, vault: Path | str) -> dict[str, Any]:
    """A bounded human/agent handoff, not a new copy or transaction engine."""
    report = verify_package(package, workspace=workspace)
    root = _directory(Path(vault))
    package_root = _directory(Path(package))
    relative = "inbox/research/" + report["evidence_id"]
    target = root / relative
    # Existing destinations are conflicts even if believed identical: inspect
    # prior provenance instead of overwriting or silently repeating ingestion.
    if target.exists() or target.is_symlink():
        raise EvidenceError("intake destination already exists; inspect previous capture")
    for parent in (root / "inbox", root / "inbox/research"):
        if parent.exists() or parent.is_symlink():
            assert_unaliased_directory(parent)
    if root == package_root or root in package_root.parents:
        raise EvidenceError("package already lies inside selected vault; inspect existing intake")
    return dict(report, schema="legends-empire.evidence-intake-plan/v1",
                vault_root=str(root), source_package=str(package_root), destination=relative,
                status="review_required", transaction=None,
                steps=["Review workspace, collection time, request settings and response state.",
                       "Reverify the package immediately before staging its three fixed members without overwrite.",
                       "Use existing capture plan, then capture apply preview and approved transaction on a supported POSIX filesystem.",
                       "Inspect immutable source locators before a separate reviewed semantic ingest."])
